<a href="https://colab.research.google.com/github/LeoMx11/Company-Valuation/blob/main/Company_Valuation_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hello! This is sort of a part two to another project I am completing with my friend Eric where we predict the change in...

In [1]:
import requests
from bs4 import BeautifulSoup

In [3]:
page = requests.get("https://stockanalysis.com/list/biggest-companies/", "html")

soup = BeautifulSoup(page.text, 'html.parser')

text = str(soup)

In [ ]:
def getHtml(url):

  page = requests.get(url, "html")

  soup = BeautifulSoup(page.text, 'html.parser')

  text = str(soup)

  return text

In [ ]:
check = 0

text1 = text

TickerList = []

while check == 0:

  text1 = text1[text1.find('<a href="/stocks/') + 1:]
  text1 = text1[text1.find('>')+1:]

  TickerList.append(text1[:text1.find('<')])

  if text1.find('<a href="/stocks/') == -1:
    check = 1

500

In [ ]:
import yfinance as yf
import pandas as pd

In [ ]:
def mostRecentQtrDate(ticker):

  return str(yf.Ticker(ticker).get_financials(freq="quarterly").keys()[0])[:10]

In [ ]:
bigDf = pd.DataFrame()

for stock in TickerList:

  concatThis = pd.DataFrame()

  try: concatThis[stock] = yf.Ticker(stock).get_financials(freq = "quarterly")[mostRecentQtrDate(stock)]
  except: pass

  try: bigDf = pd.concat([bigDf, concatThis], axis = 1)
  except: pass

bigDf.head()

AAPL  \
TaxEffectOfUnusualItems                                       0.0   
TaxRateForCalcs                                              0.21   
NormalizedEBITDA                                    45912000000.0   
NetIncomeFromContinuingOperationNetMinorityInte...  36330000000.0   
ReconciledDepreciation                               3080000000.0   
...                                                           ...   
PolicyholderBenefitsGross                                     NaN   
DepletionIncomeStatement                                      NaN   
NetIncomeFromTaxLossCarryforward                              NaN   
PolicyholderBenefitsCeded                                     NaN   
SecuritiesAmortization                                        NaN   

                                                             MSFT  \
TaxEffectOfUnusualItems                              -203220000.0   
TaxRateForCalcs                                              0.18   
NormalizedEBITDA                                    37915000000.0   
NetIncomeFromContinuingOperationNetMinorityInte...  24108000000.0   
ReconciledDepreciation                               6827000000.0   
...                                                           ...   
PolicyholderBenefitsGross                                     NaN   
DepletionIncomeStatement                                      NaN   
NetIncomeFromTaxLossCarryforward                              NaN   
PolicyholderBenefitsCeded                                     NaN   
SecuritiesAmortization                                        NaN   

                                                             NVDA  \
TaxEffectOfUnusualItems                                       0.0   
TaxRateForCalcs                                             0.135   
NormalizedEBITDA                                    22855000000.0   
NetIncomeFromContinuingOperationNetMinorityInte...  19309000000.0   
ReconciledDepreciation                                478000000.0   
...                                                           ...   
PolicyholderBenefitsGross                                     NaN   
DepletionIncomeStatement                                      NaN   
NetIncomeFromTaxLossCarryforward                              NaN   
PolicyholderBenefitsCeded                                     NaN   
SecuritiesAmortization                                        NaN   

                                                              AMZN  \
TaxEffectOfUnusualItems                            -2700449.076897   
TaxRateForCalcs                                           0.150025   
NormalizedEBITDA                                     32100000000.0   
NetIncomeFromContinuingOperationNetMinorityInte...   15328000000.0   
ReconciledDepreciation                               13442000000.0   
...                                                            ...   
PolicyholderBenefitsGross                                      NaN   
DepletionIncomeStatement                                       NaN   
NetIncomeFromTaxLossCarryforward                               NaN   
PolicyholderBenefitsCeded                                      NaN   
SecuritiesAmortization                                         NaN   

                                                            GOOGL  \
TaxEffectOfUnusualItems                               340680000.0   
TaxRateForCalcs                                              0.17   
NormalizedEBITDA                                    33741000000.0   
NetIncomeFromContinuingOperationNetMinorityInte...  26301000000.0   
ReconciledDepreciation                               3985000000.0   
...                                                           ...   
PolicyholderBenefitsGross                                     NaN   
DepletionIncomeStatement                                      NaN   
NetIncomeFromTaxLossCarryforward                              NaN   
PolicyholderBenefitsCeded                  

In [ ]:
bigDf = bigDf.fillna(0)

columnList = bigDf.columns

rowMeans = bigDf.mean(axis=1)

rowMeans

<ipython-input-9-19e2ad0c303c>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bigDf = bigDf.fillna(0)


TaxEffectOfUnusualItems                               -2.034045e+08
TaxRateForCalcs                                        1.962338e-01
NormalizedEBITDA                                       1.069576e+10
NetIncomeFromContinuingOperationNetMinorityInterest    1.150527e+10
ReconciledDepreciation                                 4.339297e+09
                                                           ...     
PolicyholderBenefitsGross                              1.241481e+08
DepletionIncomeStatement                               6.802469e+05
NetIncomeFromTaxLossCarryforward                      -7.613169e+04
PolicyholderBenefitsCeded                              1.378601e+05
SecuritiesAmortization                                -1.367078e+04
Length: 84, dtype: float64

In [ ]:
len(columnList)

bigDf = bigDf.div(rowMeans, axis=0)



In [ ]:
import torch

In [ ]:
bigTensor = torch.from_numpy(bigDf.to_numpy().transpose()).type(torch.float)

In [ ]:
bigTensor

tensor([[-0.0000e+00, 1.0702e+00, 4.2925e+00,  ..., -0.0000e+00, 0.0000e+00,
         -0.0000e+00],
        [9.9909e-01, 9.1727e-01, 3.5449e+00,  ..., -0.0000e+00, 0.0000e+00,
         -0.0000e+00],
        [-0.0000e+00, 6.8795e-01, 2.1368e+00,  ..., -0.0000e+00, 0.0000e+00,
         -0.0000e+00],
        ...,
        [5.3507e-03, 1.1721e+00, 8.7243e-02,  ..., -0.0000e+00, 0.0000e+00,
         -0.0000e+00],
        [-0.0000e+00, 1.3087e+00, 2.1708e-02,  ..., -0.0000e+00, 0.0000e+00,
         -0.0000e+00],
        [7.8661e-05, 8.1535e-02, 4.3943e-03,  ..., -0.0000e+00, 0.0000e+00,
         -0.0000e+00]])

In [ ]:
PriceList = []

i=0

for ticker in list(columnList):

  try: PriceList.append((yf.Ticker(ticker).history(period="80d")["Open"].iloc[1]))
  except:
    print(ticker + " failed")
    bigTensor = torch.cat((bigTensor[:i], bigTensor[i+1:]))
    columnList = columnList.drop(ticker)

  i+=1

print(len(PriceList))
print(len(columnList))

486
486


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
dataTrain, dataTest, priceTrain, priceTest = train_test_split(bigTensor, torch.tensor(PriceList), test_size=0.2, random_state=42)

In [ ]:
dataTrain = torch.nan_to_num(dataTrain, nan=0.0)
dataTest = torch.nan_to_num(dataTest, nan=0.0)

In [ ]:
priceTrain = priceTrain.type(torch.float)
priceTest = priceTest.type(torch.float)

In [ ]:
# import necessary stuff
import torch
from torch import nn

# make device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [ ]:
# construct model
class StockPriceModel1(nn.Module):
  def __init__(self):
    super().__init__()

    self.layer1 = nn.Linear(in_features=84,
                            out_features=20)

    self.layer2 = nn.Linear(in_features=20,
                            out_features=5)

    self.layer3 = nn.Linear(in_features=5,
                            out_features=1)

    self.relu = nn.ReLU()

  def forward(self, x):
    return self.layer3(self.layer2(self.relu(self.layer1(x))))

In [ ]:
model_0 = StockPriceModel1().to(device)
model_0.state_dict()

OrderedDict([('layer1.weight',
              tensor([[ 0.0190, -0.0284,  0.0520,  ..., -0.0084,  0.1015,  0.0285],
                      [-0.0290, -0.0660, -0.0381,  ..., -0.0758, -0.0611,  0.0598],
                      [ 0.0857, -0.0826,  0.0428,  ...,  0.0172,  0.0014,  0.0215],
                      ...,
                      [-0.0127, -0.0937, -0.0882,  ..., -0.0570,  0.0285,  0.0998],
                      [ 0.0083,  0.0988, -0.1028,  ...,  0.0547, -0.0012,  0.0275],
                      [-0.0056,  0.0977,  0.0965,  ..., -0.0370,  0.0106, -0.0648]])),
             ('layer1.bias',
              tensor([ 0.0295, -0.0051,  0.0871,  0.0683,  0.0353,  0.0913,  0.0702, -0.0770,
                       0.0012,  0.0646,  0.0497,  0.0204,  0.0833,  0.0225,  0.0330,  0.0071,
                       0.0236,  0.0080, -0.0794,  0.0489])),
             ('layer2.weight',
              tensor([[-0.0719, -0.1768,  0.1488,  0.0538,  0.1951, -0.1765,  0.2199,  0.0524,
                       -0.1141,

In [ ]:
optimizer = torch.optim.SGD(params = model_0.parameters(),
                            lr=0.001)
loss_fn = torch.nn.functional.l1_loss

In [ ]:
def accuracy_fn(priceTrue, pricePred):

  total = 0

  for i in range(len(pricePred)):
    error = torch.abs(pricePred[i]-priceTrue[i]) / priceTrue[i]
    if error < 0.4:
      total += 1

  return total / len(pricePred)



In [ ]:
nn.functional.l1_loss(torch.tensor([3.0]), torch.tensor([5.0]))

tensor(2.)

In [ ]:
epochs = 1000

for epoch in range(epochs):

  model_0.train()

  #forward pass
  price_preds = model_0(dataTrain).squeeze()

  #calculate loss
  loss = loss_fn(price_preds, priceTrain)

  acc = accuracy_fn(priceTrue=priceTrain,
                   pricePred=price_preds)

  # optimizer zero grad
  optimizer.zero_grad()

  # perform backpropagation
  loss.backward()

  # optimizer step
  optimizer.step()

  # TESTING
  model_0.eval()
  with torch.inference_mode():

    price_test_preds = model_0(dataTest).squeeze()

    test_loss = loss_fn(price_test_preds,priceTest)
    test_acc = accuracy_fn(priceTest, price_test_preds)

  if epoch % 100 == 0:
    print(f"Epoch: {epoch} | Loss: {loss} | Acc: {acc}")
    print(f"Test Loss: {test_loss} | Test acc: {test_acc}")

Epoch: 0 | Loss: 119.40908813476562 | Acc: 0.5463917525773195
Test Loss: 143.87086486816406 | Test acc: 0.40816326530612246
Epoch: 100 | Loss: 121.79678344726562 | Acc: 0.5489690721649485
Test Loss: 149.29063415527344 | Test acc: 0.3877551020408163
Epoch: 200 | Loss: 120.52303314208984 | Acc: 0.5360824742268041
Test Loss: 154.8955078125 | Test acc: 0.40816326530612246
Epoch: 300 | Loss: 121.7148666381836 | Acc: 0.5438144329896907
Test Loss: 146.0621795654297 | Test acc: 0.3979591836734694
Epoch: 400 | Loss: 117.8634033203125 | Acc: 0.5438144329896907
Test Loss: 169.03114318847656 | Test acc: 0.3673469387755102
Epoch: 500 | Loss: 127.0459213256836 | Acc: 0.5438144329896907
Test Loss: 142.14878845214844 | Test acc: 0.41836734693877553
Epoch: 600 | Loss: 126.38417053222656 | Acc: 0.5463917525773195
Test Loss: 154.7152099609375 | Test acc: 0.40816326530612246
Epoch: 700 | Loss: 127.1956787109375 | Acc: 0.5618556701030928
Test Loss: 162.23765563964844 | Test acc: 0.3979591836734694
Epoch: 8

These models only ever seem to have about as much accuracy as the error that I allow (i.e. if I say it has to be below 50% error, about 50% of the predictions will be within the range). To call this insignificant would be an understatement. Next, instead of just letting every single parameter have a say in the valuation, I will do some actual research into some valuation metrics and test which ones are the most accurate.